services:
  admin-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3001
    restart: unless-stopped
    networks:
      - admin-network

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - admin-app
    restart: unless-stopped
    networks:
      - admin-network

networks:
  admin-network:
    driver: bridge