services:
  admin-app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    ports:
      - "3001:3001"
    env_file:
      - .env
    environment:
      - NUXT_PUBLIC_API_HOST=http://api.tatroof.ru
      - NUXT_AUTH_ORIGIN=http://admin.tatroof.ru
      - NODE_ENV=production
      - HOST=0.0.0.0
      - PORT=3001
    restart: unless-stopped
    networks:
      - admin-network
      
networks:
  admin-network:
    driver: bridge